[PHP]
error_reporting = E_ALL
error_log = /dev/stderr
display_startup_errors = On
expose_php = Off

[Date]
date.timezone = UTC

[Xdebug]
xdebug.cli_color = 2
; parsing environment variables is possible thanks to parse_ini_file php function
xdebug.mode = ${X_MODE}
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.log = /var/www/app/data/log/xdebug.log
xdebug.output_dir = /var/www/app/var/log
